android.useAndroidX=true
android.builtInKotlin=true
android.newDsl=true
kotlin.code.style=official
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.nonTransitiveRClass=true

# Java toolchain (Termux)
org.gradle.java.installations.paths=/data/data/com.termux/files/usr/lib/jvm
org.gradle.java.installations.auto-download=false
